#!/usr/bin/env pybricks-micropython


fraseskid = [
    "Uau! Suas mãos mostram que você tem uma aventura incrível pela frente!",
    "A linha da sua mão diz que você é ótimo(a) em fazer novos amigos!",
    "Sabe o que suas mãos estão dizendo? Que você tem um superpoder secreto!",
    "Hmm, parece que você vai descobrir algo muito legal em breve!",
    "Sua mão me contou que você tem muita criatividade e adora desenhar ou construir coisas!",
    "Olha só, suas mãos estão dizendo que você é muito inteligente e curioso(a)!",
    "Parece que você tem uma missão especial: espalhar alegria por onde passar!",
    "Suas mãos mostram que você é um(a) aventureiro(a) que sempre descobre coisas novas!",
    "Suas mãos têm superpoderes! Consigo ver que você é capaz de criar coisas incríveis!",
    "Ahá! Essas linhas dizem que você tem uma imaginação mágica que pode transformar qualquer dia em uma aventura!",
    "Sua mão me contornou um segredo... Você vai descobrir um talento incrível muito em breve!",
    "As linhas aqui estão dizendo que você é um(a) explorador(a) destemido(a), pronto(a) para descobrir novos mundos!",
    "Uau! Parece que você é ótimo(a) em resolver mistérios e desvendar enigmas!",
    "Parece que suas mãos são cheias de coragem, prontas para enfrentar qualquer desafio com um sorriso!",
    "Eu vejo aqui que você adora aprender coisas novas e sempre está curioso(a) sobre o mundo ao seu redor!",
    "Sabia que essas linhas revelam que você tem uma energia incrível para brincar e se divertir?",
    "Parece que você está destinado(a) a realizar algo muito especial, como construir um castelo ou até salvar o dia!",
    "Suas mãos mostram que você tem o coração de um(a) grande líder, alguém que sempre cuida dos amigos!"
     "Uau! Você tem uma imaginação tão grande que pode alcançar as estrelas!",
    "Sabia que dentro de você vive um inventor(a) incrível?",
    "Parece que você vai criar algo super legal hoje!",
    "Suas mãos são mágicas, cheias de poder para transformar o mundo!",
    "Cada sorriso seu é como um raio de sol iluminando tudo ao redor!",
    "Essas mãos mostram que você é ótimo(a) em descobrir coisas novas!",
    "Eu vejo aqui que você adora brincar e se divertir o dia inteiro!",
    "Você tem o coração de um(a) verdadeiro(a) aventureiro(a)!",
    "Sua imaginação pode levar você a lugares que ninguém nunca viu!",
    "Essas linhas me dizem que você vai viver uma grande aventura em breve!",
    "Você tem o poder de transformar o ordinário em extraordinário!",
    "Suas mãos são mágicas! O que será que você vai criar hoje?",
    "Parece que você é um(a) verdadeiro(a) caçador(a) de tesouros escondidos!",
    "As linhas da sua mão mostram que você sempre encontra novas amizades!",
    "Sua curiosidade é como uma chave mágica que abre portas para novos mundos!",
    "Vejo aqui que você é um(a) artista incrível! Suas ideias vão colorir o mundo!",
    "Essas linhas me contam que você tem um talento especial para contar histórias!",
    "Você é um(a) verdadeiro(a) explorador(a), sempre em busca de novos desafios!",
    "Cada passo seu é como um salto para uma nova descoberta incrível!",
    "Você tem o poder de criar aventuras incríveis com sua imaginação!",
    "Essas linhas mostram que você é um(a) líder que inspira todos ao seu redor!",
    "Parece que você vai desvendar um mistério muito em breve!",
    "Suas mãos me dizem que você tem o coração de um(a) herói(ína)!",
    "Você tem uma energia tão grande que parece que pode mudar o mundo!",
    "Olha só, suas mãos revelam que você adora aprender coisas novas!",
    "Essas linhas dizem que você está sempre pronto(a) para uma nova aventura!",
    "Você tem a habilidade de transformar qualquer dia em algo extraordinário!",
    "Sabia que você tem uma criatividade que brilha como as estrelas?",
    "Essas mãos mostram que você está destinado(a) a criar algo incrível!",
    "Cada linha da sua mão revela que você tem um espírito aventureiro!",
    "Você é capaz de resolver qualquer mistério com sua inteligência afiada!",
    "Parece que você é ótimo(a) em fazer os outros sorrirem!",
    "Você tem o dom de transformar o simples em mágico!",
    "Essas linhas mostram que você tem o coração de um(a) verdadeiro(a) explorador(a) espacial!",
    "Sua curiosidade vai levá-lo(a) a lugares incríveis e cheios de mistérios!",
    "Você está destinado(a) a viver uma grande aventura muito em breve!",
    "Suas mãos mostram que você adora criar novas brincadeiras com os amigos!",
    "Você tem uma habilidade mágica de transformar qualquer desafio em diversão!",
    "Essas mãos revelam que você é ótimo(a) em construir coisas incríveis!",
    "Parece que você tem o dom de trazer felicidade para todos ao seu redor!",
    "Vejo aqui que você está sempre em busca de novas aventuras emocionantes!",
    "Suas mãos mostram que você é um(a) verdadeiro(a) inventor(a) de sonhos!",
    "Você tem um poder especial de fazer novos amigos em qualquer lugar!",
    "Essas linhas dizem que você vai descobrir algo muito especial em breve!",
    "Sabia que você tem o coração de um(a) super-herói(ína)?",
    "Suas mãos estão cheias de energia mágica para criar coisas maravilhosas!",
    "Olha só, parece que você vai encontrar um tesouro muito especial!",
    "Vejo aqui que você é excelente em resolver mistérios e enigmas!",
    "Você tem o poder de transformar o ordinário em extraordinário com sua imaginação!",
    "Essas linhas mostram que você adora explorar novos lugares e fazer descobertas incríveis!",
    "Parece que você tem o coração de um(a) verdadeiro(a) aventureiro(a) do espaço!",
    "Sabia que você está destinado(a) a construir coisas que ninguém jamais imaginou?",
    "Essas mãos revelam que você é um(a) verdadeiro(a) cientista do futuro!",
    "Suas mãos mostram que você tem uma energia tão grande que pode mudar o mundo!",
    "Parece que você está pronto(a) para enfrentar qualquer desafio com um sorriso!",
    "Essas linhas revelam que você tem o dom de contar histórias que encantam a todos!",
    "Você tem uma imaginação tão poderosa que pode criar mundos inteiros!",
    "Sabia que você é excelente em resolver problemas e encontrar soluções criativas?",
    "Essas mãos mostram que você tem o dom de trazer alegria para todos ao seu redor!",
    "Você tem uma habilidade especial de transformar o simples em algo incrível!",
    "Essas linhas revelam que você está destinado(a) a realizar coisas extraordinárias!",
    "Parece que você adora brincar e descobrir coisas novas todos os dias!",
    "Sabia que você tem o dom de transformar qualquer dia chato em uma grande aventura?",
    "Essas mãos mostram que você é ótimo(a) em fazer novos amigos e se divertir!",
    "Você tem o poder de transformar sua imaginação em realidade!",
    "Essas linhas revelam que você tem um talento especial para criar coisas incríveis!",
    "Parece que você está sempre pronto(a) para uma nova missão de exploração!",
    "Sabia que você tem o coração de um(a) verdadeiro(a) aventureiro(a) do espaço sideral?",
    "Essas mãos mostram que você tem o dom de criar histórias mágicas!",
    "Você tem uma energia tão grande que parece que pode transformar o mundo!",
    "Essas linhas revelam que você está destinado(a) a fazer algo muito especial!",
    "Parece que você vai viver uma grande aventura em breve!",
    "Essas mãos mostram que você é um(a) verdadeiro(a) inventor(a) de coisas incríveis!",
    "Sabia que você tem o dom de resolver enigmas e mistérios como um(a) detetive?",
    "Essas linhas mostram que você tem uma imaginação tão grande que pode alcançar o céu!",
    "Você tem o poder de transformar qualquer desafio em diversão!",
    "Essas mãos revelam que você é excelente em criar novas brincadeiras com os amigos!",
    "Parece que você está sempre pronto(a) para explorar novos mundos!",
    "Sabia que você tem o dom de trazer alegria para todos ao seu redor?",
    "Essas linhas mostram que você é um(a) verdadeiro(a) herói(ína) em treinamento!",
    "Você tem uma energia tão grande que parece que pode transformar qualquer lugar em um parque de diversões!",
    "Essas mãos revelam que você tem o dom de criar coisas incríveis com suas próprias mãos!",
    "Parece que você está destinado(a) a realizar grandes coisas no futuro!",
    "Essas linhas mostram que você adora explorar e descobrir novos segredos!",
    "Sabia que você tem o dom de transformar o simples em algo mágico?",
    "Essas mãos revelam que você é excelente em resolver problemas de forma criativa!",
    "Você tem o poder de transformar o mundo com sua imaginação poderosa!",
    "Essas linhas mostram que você é um(a) verdadeiro(a) inventor(a) de sonhos e ideias!",
    "Parece que você vai encontrar uma grande aventura muito em breve!",
    "Sabia que você está destinado(a) a criar coisas que ninguém jamais imaginou?",
    "Essas mãos revelam que você tem o dom de transformar o ordinário em algo extraordinário!",
    "Você tem o poder de trazer alegria para todos ao seu redor com sua energia contagiante!",
    "Essas linhas mostram que você é um(a) verdadeiro(a) explorador(a) pronto(a) para grandes descobertas!",
    "Parece que você tem uma imaginação tão grande que pode transformar qualquer dia em uma aventura mágica!",
    "Sabia que você tem o dom de resolver enigmas e mistérios como um(a) verdadeiro(a) detetive?",
    "Essas mãos revelam que você tem o dom de criar novas brincadeiras que encantam todos ao redor!",
    "Você tem o poder de transformar o mundo com sua criatividade!",
    "Essas linhas mostram que você é um(a) verdadeiro(a) inventor(a) de grandes ideias!",
    "Parece que você está pronto(a) para enfrentar qualquer desafio com coragem e determinação!",
    "Sabia que você tem o dom de contar histórias que fazem todos sonharem?",
    "Essas mãos revelam que você é excelente em resolver mistérios e encontrar soluções brilhantes!",
    "Você tem o poder de transformar qualquer lugar em um mundo cheio de magia!",
    "Essas linhas mostram que você é um(a) verdadeiro(a) aventureiro(a), sempre descobrindo novos segredos!",
    "Parece que você tem uma energia tão grande que pode iluminar o mundo com suas ideias!",
    "Sabia que você está destinado(a) a realizar grandes coisas no futuro?",
    "Essas mãos revelam que você tem o dom de criar coisas incríveis com sua imaginação!",
    "Você tem o poder de transformar qualquer dia comum em uma aventura extraordinária!",
    "Essas linhas mostram que você adora explorar novos mundos e descobrir segredos escondidos!",
     "Sabia que suas mãos estão cheias de estrelas, prontas para brilhar?",
    "Essas linhas mostram que você é um(a) explorador(a) de sonhos!",
    "Você tem um talento incrível para resolver qualquer desafio com um sorriso!",
    "Essas mãos me dizem que você é ótimo(a) em criar histórias mágicas!",
    "Vejo aqui que você adora descobrir mistérios e resolver enigmas!",
    "Você tem o poder de transformar qualquer lugar em um parque de diversão!",
    "Essas linhas mostram que você está destinado(a) a ser um(a) inventor(a) incrível!",
    "Parece que você tem um talento secreto prestes a ser descoberto!",
    "Suas mãos revelam que você tem o coração de um(a) herói(ína) que adora aventuras!",
    "Sabia que você tem uma imaginação tão poderosa que pode transformar o mundo?",
    "Essas mãos mostram que você é ótimo(a) em criar novas brincadeiras!",
    "Você está prestes a descobrir algo muito especial e mágico!",
    "Essas linhas revelam que você tem o poder de resolver mistérios com facilidade!",
    "Parece que você tem uma energia mágica para espalhar alegria por onde passa!",
    "Sabia que suas mãos dizem que você está destinado(a) a grandes aventuras?",
    "Essas linhas mostram que você tem uma imaginação cheia de surpresas!",
    "Você tem o dom de transformar qualquer dia comum em algo extraordinário!",
    "Essas mãos me dizem que você é um(a) verdadeiro(a) aventureiro(a)!",
    "Parece que você está sempre pronto(a) para explorar novos mundos!",
    "Suas mãos revelam que você tem uma energia contagiante que ilumina tudo ao seu redor!",
    "Sabia que você tem o coração de um(a) verdadeiro(a) líder?",
    "Essas linhas mostram que você tem uma curiosidade imensa por aprender coisas novas!",
    "Você tem o poder de transformar qualquer problema em uma oportunidade de diversão!",
    "Essas mãos revelam que você é ótimo(a) em fazer novos amigos e compartilhar aventuras!",
    "Parece que você está destinado(a) a descobrir algo muito especial!",
    "Sabia que sua imaginação é tão grande que pode alcançar o infinito?",
    "Essas linhas mostram que você tem um espírito aventureiro, sempre em busca de novos desafios!",
    "Você tem o poder de trazer felicidade para todos ao seu redor com seu sorriso!",
    "Essas mãos revelam que você tem um talento incrível para criar histórias e personagens!",
    "Parece que você está prestes a embarcar em uma grande aventura!",
    "Suas mãos mostram que você adora explorar e fazer novas descobertas!",
    "Sabia que você tem uma energia tão grande que parece que pode mudar o mundo?",
    "Essas linhas revelam que você tem um espírito de liderança natural!",
    "Você tem o poder de transformar qualquer situação em algo divertido e emocionante!",
    "Essas mãos mostram que você adora descobrir segredos escondidos!",
    "Parece que você está destinado(a) a criar algo muito especial no futuro!",
    "Suas mãos revelam que você tem uma imaginação mágica que pode criar qualquer coisa!",
    "Sabia que você é ótimo(a) em resolver enigmas e mistérios com facilidade?",
    "Essas linhas mostram que você tem o dom de contar histórias que encantam todos!",
    "Você tem o poder de transformar qualquer lugar em um mundo cheio de aventuras!",
    "Essas mãos revelam que você tem uma energia mágica para descobrir novos mistérios!",
    "Parece que você está prestes a fazer uma descoberta incrível!",
    "Suas mãos mostram que você tem o coração de um(a) herói(ína) que adora desafios!",
    "Sabia que você tem um talento especial para criar coisas incríveis?",
    "Essas linhas revelam que você tem o dom de transformar o simples em algo mágico!",
    "Você tem o poder de transformar qualquer brincadeira em uma grande aventura!",
    "Essas mãos mostram que você adora explorar novos mundos e fazer descobertas fantásticas!",
    "Parece que você está sempre pronto(a) para uma nova missão!",
    "Suas mãos revelam que você tem uma energia cheia de alegria e diversão!",
    "Sabia que você tem o coração de um(a) explorador(a) do espaço?",
    "Essas linhas mostram que você tem o dom de criar histórias mágicas que encantam a todos!",
    "Você tem o poder de transformar qualquer dia comum em uma aventura extraordinária!",
    "Essas mãos revelam que você tem uma imaginação incrível para criar novos mundos!",
    "Parece que você está prestes a embarcar em uma grande aventura espacial!",
    "Suas mãos mostram que você é ótimo(a) em resolver desafios e enigmas!",
    "Sabia que você tem o poder de trazer alegria para todos ao seu redor com sua energia contagiante?",
    "Essas linhas mostram que você tem um talento especial para inventar coisas!",
    "Você tem o poder de transformar o mundo com sua imaginação mágica!",
    "Essas mãos revelam que você adora explorar novos lugares e descobrir segredos!",
    "Parece que você está destinado(a) a fazer algo incrível e inesquecível!",
    "Suas mãos mostram que você tem uma energia cheia de aventura e curiosidade!",
    "Sabia que você tem o coração de um(a) verdadeiro(a) inventor(a)?",
    "Essas linhas mostram que você tem o dom de resolver problemas de forma criativa!",
    "Você tem o poder de transformar qualquer dia comum em uma experiência extraordinária!",
    "Essas mãos revelam que você é excelente em criar novas brincadeiras e aventuras!",
    "Parece que você está pronto(a) para descobrir algo mágico em breve!",
    "Suas mãos mostram que você tem um talento incrível para fazer novos amigos!",
    "Sabia que você está destinado(a) a viver grandes aventuras cheias de mistério e diversão?",
    "Essas linhas revelam que você tem uma imaginação mágica que transforma o mundo ao seu redor!",
    "Você tem o poder de transformar o simples em algo extraordinário com sua criatividade!",
    "Essas mãos mostram que você adora explorar e fazer novas descobertas incríveis!",
    "Parece que você está sempre pronto(a) para enfrentar novos desafios com um sorriso!",
    "Suas mãos revelam que você tem o dom de criar aventuras mágicas cheias de emoção!",
    "Sabia que você tem uma energia tão grande que pode mudar o mundo com suas ideias?",
    "Essas linhas mostram que você está destinado(a) a realizar grandes coisas!",
    "Você tem o poder de transformar qualquer brincadeira em uma grande aventura cheia de surpresas!",
    "Essas mãos revelam que você adora descobrir segredos escondidos em lugares misteriosos!",
    "Parece que você vai embarcar em uma grande jornada cheia de emoções!",
    "Suas mãos mostram que você é ótimo(a) em criar novas histórias e personagens incríveis!",
    "Sabia que você tem uma imaginação mágica que pode criar qualquer coisa?",
    "Essas linhas mostram que você tem o dom de resolver desafios com facilidade e diversão!",
    "Você tem o poder de transformar qualquer lugar em um mundo cheio de aventuras mágicas!",
    "Essas mãos revelam que você adora explorar novos mundos e fazer descobertas fantásticas!",
    "Parece que você está prestes a descobrir algo muito especial e mágico!",
    "Suas mãos mostram que você tem o coração de um(a) verdadeiro(a) aventureiro(a)!",
    "Sabia que você tem o talento de transformar qualquer desafio em uma oportunidade de diversão?",
    "Essas linhas revelam que você está destinado(a) a viver grandes aventuras cheias de mistério!",
    "Você tem o poder de transformar o simples em algo mágico com sua imaginação poderosa!",
    "Essas mãos mostram que você adora explorar e descobrir segredos escondidos em todos os lugares!",
    "Parece que você está sempre pronto(a) para enfrentar novos desafios com coragem e alegria!"
]