#!/usr/bin/env pybricks-micropython

import os
from colorama import init, Fore, Back

frasesIA = [
    "Você tem muitas escolhas à sua frente.",
    "Seu caminho será definido por suas ações em breve.",
    "Vejo uma mudança inesperada em sua vida pessoal.",
    "Alguém de quem você gosta muito está pensando em você.",
    "O sucesso depende de uma decisão que você ainda vai tomar.",
    "Uma pessoa do passado vai reaparecer.",
    "Há algo que você deseja há muito tempo que está ao seu alcance.",
    "Seu esforço será recompensado em breve.",
    "Você tem um forte senso de responsabilidade.",
    "As pessoas ao seu redor confiam em você mais do que você imagina.",
    "Uma oportunidade vai surgir quando você menos esperar.",
    "Você terá que fazer uma escolha importante em breve.",
    "Alguém com quem você perdeu o contato voltará a se aproximar.",
    "Um desafio está no horizonte, mas você vai superá-lo.",
    "Você vai descobrir algo novo sobre uma pessoa próxima.",
    "Seu trabalho duro logo dará frutos.",
    "Você está em uma fase de adaptação e mudanças.",
    "Uma pessoa inesperada vai te apoiar em breve.",
    "Você terá que ser paciente para ver os resultados que deseja.",
    "A confiança que você tem em alguém será justificada.",
    "Algo que você deixou de lado será retomado com sucesso.",
    "Sua dedicação será notada por quem importa.",
    "Vejo uma fase de crescimento pessoal à sua frente.",
    "Alguém em sua vida está buscando seu conselho.",
    "Uma decisão financeira será necessária em breve.",
    "Você tem mais capacidade do que reconhece.",
    "Seus planos estão se encaminhando, mesmo que pareça lento.",
    "Um detalhe importante será revelado quando você menos esperar.",
    "Você terá que agir com sabedoria diante de uma escolha difícil.",
    "Há algo que você está ignorando, mas logo perceberá.",
    "Sua capacidade de adaptação será testada, mas você terá sucesso.",
    "Você vai fazer uma descoberta importante sobre si mesmo.",
    "Uma conversa em breve trará clareza sobre algo que te preocupa.",
    "Você será chamado a assumir mais responsabilidades.",
    "Um contato distante será renovado em breve.",
    "Você pode estar subestimando seu próprio potencial.",
    "Algo importante que você espera vai se resolver logo.",
    "Vejo uma fase de estabilidade se aproximando.",
    "Você encontrará soluções para problemas que parecem complexos.",
    "Você precisa dedicar mais tempo a algo que tem ignorado.",
    "Seu talento será reconhecido de forma inesperada.",
    "Você terá uma oportunidade de recomeçar em um aspecto da sua vida.",
    "Alguém está mais interessado no seu sucesso do que você pensa.",
    "Uma pequena mudança pode trazer grandes resultados.",
    "Você está a um passo de conquistar algo importante.",
    "Você verá uma situação complicada de uma nova perspectiva em breve.",
    "Uma surpresa agradável está a caminho.",
    "Vejo uma mudança em sua vida profissional.",
    "Você será capaz de superar um obstáculo que parece difícil.",
    "As pessoas ao seu redor vão se surpreender com algo que você fará.",
    "Alguém que você admira vai te dar um conselho valioso.",
    "Uma fase mais tranquila está por vir.",
    "Você vai precisar se adaptar a uma nova circunstância.",
    "Seu esforço será notado por quem você menos espera.",
    "Vejo um projeto sendo finalizado com sucesso.",
    "Você vai ganhar mais clareza sobre algo que tem sido confuso.",
    "Um evento recente mudará sua forma de pensar.",
    "Sua habilidade de resolver problemas será testada.",
    "Alguém próximo a você passará por uma fase difícil e precisará de sua ajuda.",
    "Você vai se destacar em uma situação inesperada.",
    "As respostas que você procura estão mais perto do que você imagina.",
    "Algo que você deseja vai acontecer quando você menos esperar.",
    "Um novo contato vai abrir portas para você.",
    "Você está mais perto de atingir seus objetivos do que pensa.",
    "Você terá uma oportunidade de mostrar seu verdadeiro potencial.",
    "Uma mudança na sua rotina trará benefícios.",
    "Um novo desafio surgirá, mas você terá apoio para superá-lo.",
    "Você será chamado a tomar uma atitude importante.",
    "Você terá uma conversa esclarecedora com alguém importante.",
    "Algo que estava em segundo plano vai se tornar mais importante.",
    "Um problema vai se resolver de uma forma inesperada.",
    "Você vai reencontrar algo que pensou ter perdido.",
    "As pessoas vão começar a perceber suas capacidades de forma mais clara.",
    "Você terá que tomar uma decisão importante relacionada a um projeto pessoal.",
    "Alguém em quem você não esperava confiar te surpreenderá.",
    "Uma nova fase começará em breve em sua vida pessoal.",
    "Algo que parecia difícil vai se resolver com mais facilidade do que você pensava.",
    "Você vai conseguir equilibrar uma situação complicada.",
    "Vejo uma oportunidade de aprender algo novo se aproximando.",
    "Você está em uma fase de preparação para algo maior.",
    "Uma oferta inesperada surgirá e te fará repensar planos.",
    "Algo que te preocupava vai se resolver em breve.",
    "Vejo uma fase de reconhecimento pelo seu trabalho.",
    "Você terá que ajustar seus planos para aproveitar melhor as oportunidades.",
    "Alguém com quem você perdeu contato vai voltar a se aproximar.",
    "Você vai precisar de paciência para lidar com uma situação desafiadora.",
    "Vejo uma mudança importante em seus relacionamentos.",
    "Um projeto que parecia distante vai se aproximar da conclusão.",
    "Você será chamado a fazer algo fora da sua zona de conforto.",
    "Vejo uma oportunidade de crescer em sua vida profissional.",
    "Você vai perceber algo importante em breve.",
    "Uma pessoa que você admira vai te surpreender.",
    "Algo pequeno que você ignorou vai se tornar mais significativo.",
    "Você está no caminho certo para alcançar o que deseja.",
    "Alguém que você não esperava vai te dar uma boa notícia.",
    "Você terá que se preparar para lidar com um desafio inesperado.",
    "Alguém com quem você tem pouco contato vai se tornar mais presente em sua vida."
]


init()


os.system('cls')
print(Fore.BLUE + frasesIA[4])

