#!/usr/bin/env pybricks-micropython


frasesExtra = [
    "Você vai ter que reconsiderar uma decisão recente.",
    "Algo que parecia resolvido pode voltar à tona em breve.",
    "Uma pequena mudança na sua rotina trará grandes resultados.",
    "Você receberá uma notícia que não esperava.",
    "Alguém de quem você não ouve há muito tempo vai entrar em contato.",
    "Você está perto de finalizar algo importante.",
    "Uma situação difícil logo se tornará mais clara.",
    "Você pode estar ignorando algo que merece sua atenção.",
    "Vejo um projeto chegando ao fim com sucesso.",
    "Alguém vai te surpreender com uma atitude inesperada.",
    "Você perceberá uma nova oportunidade onde não esperava.",
    "Sua paciência será recompensada de maneira inesperada.",
    "Alguém que você admira vai reconhecer seu esforço.",
    "Um pequeno detalhe vai fazer grande diferença em breve.",
    "Você terá que tomar uma decisão importante com base em novas informações.",
    "Seu tempo de espera logo chegará ao fim.",
    "Um relacionamento seu vai passar por uma fase de renovação.",
    "Você vai ter que equilibrar múltiplas responsabilidades.",
    "Vejo uma oportunidade de crescimento inesperado.",
    "Uma ideia que você teve há muito tempo vai se concretizar.",
    "Algo importante vai se revelar quando você estiver mais preparado.",
    "Você será chamado a tomar uma atitude proativa.",
    "Um conselho de alguém próximo será muito útil em breve.",
    "Uma pessoa com quem você não fala muito vai te procurar.",
    "Uma nova oportunidade vai surgir e te fazer repensar seus planos.",
    "Você vai ter que lidar com uma mudança que não esperava.",
    "Seu esforço será recompensado, mesmo que demore um pouco.",
    "Uma decisão sua terá mais impacto do que você imagina.",
    "Você vai precisar se adaptar rapidamente a uma nova circunstância.",
    "Algo que parecia difícil vai se resolver mais facilmente do que você pensava.",
    "Vejo uma fase de transição em sua vida profissional.",
    "Você vai perceber que está no caminho certo em breve.",
    "Alguém próximo vai te surpreender positivamente.",
    "Você terá que reavaliar suas prioridades em breve.",
    "Um desafio vai te fazer crescer de maneiras inesperadas.",
    "Uma oportunidade inesperada vai aparecer quando você menos esperar.",
    "Você encontrará uma solução criativa para um problema recorrente.",
    "Alguém próximo vai te pedir ajuda com uma questão importante.",
    "Você terá que tomar uma decisão difícil, mas necessária.",
    "Algo que você esperava vai acontecer de uma forma diferente do que imaginava.",
    "Você vai receber boas notícias em breve.",
    "Alguém vai te oferecer um conselho que será útil mais tarde.",
    "Um acontecimento recente trará mudanças em seus planos.",
    "Você será reconhecido por seu esforço em breve.",
    "Algo que você ignorava vai ganhar importância em breve.",
    "Uma pessoa com quem você não esperava contar vai te apoiar.",
    "Uma nova etapa está se aproximando e trará desafios.",
    "Você vai perceber uma nova oportunidade em uma situação comum.",
    "Algo que parecia um problema vai se revelar uma solução.",
    "Você terá que se concentrar mais em algo que estava em segundo plano.",
    "Uma decisão sua vai mudar o rumo de uma situação importante.",
    "Você receberá apoio de alguém inesperado.",
    "Alguém vai pedir seu conselho sobre uma questão delicada.",
    "Você vai se destacar em algo que não esperava.",
    "Uma oportunidade que você pensou ter perdido vai reaparecer.",
    "Algo que te preocupava vai se resolver sem esforço extra.",
    "Uma mudança em seu ambiente pessoal trará benefícios.",
    "Você terá que tomar uma atitude proativa em breve.",
    "Um detalhe importante será revelado quando você menos esperar.",
    "Você será chamado a assumir mais responsabilidade.",
    "Um projeto antigo vai ganhar novo fôlego em breve.",
    "Você perceberá que algo que parecia difícil já está resolvido.",
    "Uma conversa recente vai te ajudar a ver as coisas de outra maneira.",
    "Você vai reencontrar alguém importante em breve.",
    "Alguém vai te oferecer uma oportunidade inesperada.",
    "Uma ideia antiga voltará à tona com mais força.",
    "Você perceberá que está mais preparado do que pensava.",
    "Algo que você adiou vai ser resolvido de forma tranquila.",
    "Um encontro inesperado trará novas perspectivas.",
    "Você receberá reconhecimento por algo que fez recentemente.",
    "Uma situação que parecia estagnada vai começar a avançar.",
    "Você terá que se adaptar a uma nova realidade.",
    "Alguém com quem você trabalha vai reconhecer seu esforço.",
    "Um novo projeto ou ideia vai se apresentar em breve.",
    "Você terá que tomar uma decisão em breve que vai afetar o longo prazo.",
    "Vejo uma fase de reorganização chegando em sua vida.",
    "Você vai se surpreender com a rapidez com que algo se resolve.",
    "Uma pequena atitude vai ter grande impacto nos próximos dias.",
    "Você vai precisar de paciência para lidar com algo que está por vir.",
    "Um desafio recente vai se mostrar mais simples do que parecia.",
    "Você vai perceber que está no caminho certo.",
    "Alguém de quem você gosta vai te procurar para conversar.",
    "Uma nova perspectiva vai mudar a forma como você vê uma situação.",
    "Você vai precisar ajustar suas prioridades em breve.",
    "Vejo uma fase de estabilidade e crescimento à sua frente.",
    "Você vai reencontrar algo que pensava estar perdido.",
    "Alguém vai te oferecer uma ajuda inesperada.",
    "Você perceberá que está mais próximo de seus objetivos do que imagina.",
    "Uma decisão recente vai começar a mostrar resultados.",
    "Você será surpreendido por uma notícia que não esperava.",
    "Uma pessoa próxima vai precisar de seu apoio.",
    "Um projeto em andamento vai exigir sua atenção especial.",
    "Você vai precisar ser mais flexível para se adaptar a uma nova situação.",
    "Alguém que você admira vai se aproximar de você.",
    "Uma conversa importante vai esclarecer algo que te preocupava.",
    "Você perceberá que está mais forte do que pensava.",
    "Um evento inesperado vai mudar a forma como você vê as coisas.",
    "Você vai tomar uma decisão que vai impactar seus planos futuros.",
    "Alguém com quem você trabalha vai te fazer uma proposta.",
    "Você perceberá que algo que te preocupava já foi resolvido.",
    "Uma pessoa que você admira vai reconhecer seu esforço.",
    "Um pequeno passo que você der vai trazer grandes mudanças.",
    "Você vai descobrir uma nova forma de lidar com um problema antigo.",
    "Um reencontro com alguém do passado trará novas possibilidades.",
    "Você será surpreendido por uma atitude inesperada de alguém próximo.",
    "Algo que parecia distante vai se tornar mais acessível.",
    "Você terá que tomar uma atitude para garantir seu sucesso.",
    "Alguém vai te procurar para resolver uma questão pendente.",
    "Você será reconhecido por sua dedicação e esforço.",
    "Uma mudança de planos vai te beneficiar mais do que você imagina.",
    "Você perceberá que algo que parecia perdido ainda está ao seu alcance.",
    "Alguém vai te procurar com uma oferta que vai te surpreender.",
    "Você vai receber uma notícia que mudará sua perspectiva.",
    "Uma situação complicada vai se resolver mais facilmente do que você espera.",
    "Você perceberá que algo que parecia negativo trará benefícios.",
    "Um novo contato vai abrir portas para novas oportunidades.",
    "Uma pequena mudança trará grandes avanços em breve.",
    "Você vai perceber que tem mais apoio do que imaginava.",
    "Alguém próximo vai precisar de sua orientação em breve.",
    "Uma conversa esclarecedora vai te trazer paz de espírito.",
    "Você vai se destacar em uma situação que não esperava.",
    "Um acontecimento recente vai mudar seus planos.",
    "Você vai precisar ajustar seus objetivos para alcançar o sucesso.",
    "Alguém com quem você não fala há algum tempo vai te procurar.",
    "Um detalhe importante vai fazer toda a diferença em breve.",
    "Você perceberá que está mais perto de alcançar o que deseja.",
    "Uma nova oportunidade vai surgir de onde você menos esperava.",
    "Você vai ser chamado a resolver uma questão que estava pendente.",
    "Alguém vai te surpreender com uma atitude positiva.",
    "Um novo desafio vai te fazer crescer pessoalmente.",
    "Uma mudança em sua vida pessoal vai trazer mais equilíbrio.",
    "Você terá que tomar uma decisão importante sobre um projeto.",
    "Alguém vai te oferecer um apoio que você não esperava.",
    "Um detalhe importante será revelado e mudará sua perspectiva.",
    "Você perceberá que algo que te preocupava já foi resolvido.",
    "Alguém que você considera importante vai te dar um novo conselho.",
    "Uma oportunidade que você pensou ter perdido vai reaparecer.",
    "Você vai receber uma notícia que trará novos desafios.",
    "Algo que parecia difícil vai ser resolvido mais facilmente do que imaginava.",
    "Você será chamado a assumir uma nova responsabilidade em breve.",
    "Alguém vai te procurar para resolver uma questão pendente."
]


