#!/usr/bin/env pybricks-micropython


frasesIA = [
    "Você tem muitas escolhas à sua frente.",
    "Seu caminho será definido por suas ações em breve.",
    "Vejo uma mudança inesperada em sua vida pessoal.",
    "Alguém de quem você gosta muito está pensando em você.",
    "O sucesso depende de uma decisão que você ainda vai tomar.",
    "Uma pessoa do passado vai reaparecer.",
    "Há algo que você deseja há muito tempo que está ao seu alcance.",
    "Seu esforço será recompensado em breve.",
    "Você tem um forte senso de responsabilidade.",
    "As pessoas ao seu redor confiam em você mais do que você imagina.",
    "Uma oportunidade vai surgir quando você menos esperar.",
    "Você terá que fazer uma escolha importante em breve.",
    "Alguém com quem você perdeu o contato voltará a se aproximar.",
    "Um desafio está no horizonte, mas você vai superá-lo.",
    "Você vai descobrir algo novo sobre uma pessoa próxima.",
    "Seu trabalho duro logo dará frutos.",
    "Você está em uma fase de adaptação e mudanças.",
    "Uma pessoa inesperada vai te apoiar em breve.",
    "Você terá que ser paciente para ver os resultados que deseja.",
    "A confiança que você tem em alguém será justificada.",
    "Algo que você deixou de lado será retomado com sucesso.",
    "Sua dedicação será notada por quem importa.",
    "Vejo uma fase de crescimento pessoal à sua frente.",
    "Alguém em sua vida está buscando seu conselho.",
    "Uma decisão financeira será necessária em breve.",
    "Você tem mais capacidade do que reconhece.",
    "Seus planos estão se encaminhando, mesmo que pareça lento.",
    "Um detalhe importante será revelado quando você menos esperar.",
    "Você terá que agir com sabedoria diante de uma escolha difícil.",
    "Há algo que você está ignorando, mas logo perceberá.",
    "Sua capacidade de adaptação será testada, mas você terá sucesso.",
    "Você vai fazer uma descoberta importante sobre si mesmo.",
    "Uma conversa em breve trará clareza sobre algo que te preocupa.",
    "Você será chamado a assumir mais responsabilidades.",
    "Um contato distante será renovado em breve.",
    "Você pode estar subestimando seu próprio potencial.",
    "Algo importante que você espera vai se resolver logo.",
    "Vejo uma fase de estabilidade se aproximando.",
    "Você encontrará soluções para problemas que parecem complexos.",
    "Você precisa dedicar mais tempo a algo que tem ignorado.",
    "Seu talento será reconhecido de forma inesperada.",
    "Você terá uma oportunidade de recomeçar em um aspecto da sua vida.",
    "Alguém está mais interessado no seu sucesso do que você pensa.",
    "Uma pequena mudança pode trazer grandes resultados.",
    "Você está a um passo de conquistar algo importante.",
    "Você verá uma situação complicada de uma nova perspectiva em breve.",
    "Uma surpresa agradável está a caminho.",
    "Vejo uma mudança em sua vida profissional.",
    "Você será capaz de superar um obstáculo que parece difícil.",
    "As pessoas ao seu redor vão se surpreender com algo que você fará.",
    "Alguém que você admira vai te dar um conselho valioso.",
    "Uma fase mais tranquila está por vir.",
    "Você vai precisar se adaptar a uma nova circunstância.",
    "Seu esforço será notado por quem você menos espera.",
    "Vejo um projeto sendo finalizado com sucesso.",
    "Você vai ganhar mais clareza sobre algo que tem sido confuso.",
    "Um evento recente mudará sua forma de pensar.",
    "Sua habilidade de resolver problemas será testada.",
    "Alguém próximo a você passará por uma fase difícil e precisará de sua ajuda.",
    "Você vai se destacar em uma situação inesperada.",
    "As respostas que você procura estão mais perto do que você imagina.",
    "Algo que você deseja vai acontecer quando você menos esperar.",
    "Um novo contato vai abrir portas para você.",
    "Você está mais perto de atingir seus objetivos do que pensa.",
    "Você terá uma oportunidade de mostrar seu verdadeiro potencial.",
    "Uma mudança na sua rotina trará benefícios.",
    "Um novo desafio surgirá, mas você terá apoio para superá-lo.",
    "Você será chamado a tomar uma atitude importante.",
    "Você terá uma conversa esclarecedora com alguém importante.",
    "Algo que estava em segundo plano vai se tornar mais importante.",
    "Um problema vai se resolver de uma forma inesperada.",
    "Você vai reencontrar algo que pensou ter perdido.",
    "As pessoas vão começar a perceber suas capacidades de forma mais clara.",
    "Você terá que tomar uma decisão importante relacionada a um projeto pessoal.",
    "Alguém em quem você não esperava confiar te surpreenderá.",
    "Uma nova fase começará em breve em sua vida pessoal.",
    "Algo que parecia difícil vai se resolver com mais facilidade do que você pensava.",
    "Você vai conseguir equilibrar uma situação complicada.",
    "Vejo uma oportunidade de aprender algo novo se aproximando.",
    "Você está em uma fase de preparação para algo maior.",
    "Uma oferta inesperada surgirá e te fará repensar planos.",
    "Algo que te preocupava vai se resolver em breve.",
    "Vejo uma fase de reconhecimento pelo seu trabalho.",
    "Você terá que ajustar seus planos para aproveitar melhor as oportunidades.",
    "Alguém com quem você perdeu contato vai voltar a se aproximar.",
    "Você vai precisar de paciência para lidar com uma situação desafiadora.",
    "Vejo uma mudança importante em seus relacionamentos.",
    "Um projeto que parecia distante vai se aproximar da conclusão.",
    "Você será chamado a fazer algo fora da sua zona de conforto.",
    "Vejo uma oportunidade de crescer em sua vida profissional.",
    "Você vai perceber algo importante em breve.",
    "Uma pessoa que você admira vai te surpreender.",
    "Algo pequeno que você ignorou vai se tornar mais significativo.",
    "Você está no caminho certo para alcançar o que deseja.",
    "Alguém que você não esperava vai te dar uma boa notícia.",
    "Você terá que se preparar para lidar com um desafio inesperado.",
    "Alguém com quem você tem pouco contato vai se tornar mais presente em sua vida."
    "O futuro parece promissor para você, continue nesse caminho!",
    "Vejo grandes oportunidades chegando em breve.",
    "Você possui uma energia muito positiva ao seu redor.",
    "Prepare-se para surpresas encontradas nos próximos dias.",
    "Sua linha da fortuna está bem marcada... talvez seja hora de jogar na loteria!",
    "Esses novos sentimentos revelam um momento de indecisão, uma escolha que moldará não apenas o seu caminho, mas sua essência.",
    "As delicadas marcas em sua linha da cabeça sugerem um intelecto que busca mais do que respostas; você busca sabedoria.",
    "Sua linha do destino se ergue com força, mostrando que você não é alguém que se conforma, mas alguém que molda seu próprio destino.",
    "Vejo aqui que a jornada da sua alma está longe de acabar. Cada passo que você dá é uma dança entre o que foi e o que ainda será.",
    "Existe uma marca aqui que não pertence ao tempo presente, como se o eco de uma vida passada ainda estivesse ao seu lado.",
    "O que está escrito em sua mão não é apenas o seu destino, mas um reflexo de quem você se tornou através dos desafios e vitórias.",
    "Há um brilho oculto em sua linha da fortuna, algo que sugere que sua verdadeira riqueza não é intangível.",
    "O universo não escreve o destino, ele apenas oferece um quadro em branco. O pincel está nas suas mãos.",
    "Vejo nas suas linhas a promessa de um futuro que só poderá ser realizado quando você confiar plenamente em sua própria força.",
    "Os caminhos traçados aqui não são estáticos, são dinâmicos, movidos pelas suas decisões. O que você vai escolher?",
    "O destino se dobra diante daqueles que ousam questionar. Vejo que suas mãos carregam essa coragem.",
    "Assim como as estrelas moldam constelações, as linhas em suas mãos moldam a jornada da sua vida. Tudo está interligado.",
    "As linhas suaves da sua palma revelam um coração que anseia por um amor tranquilo e seguro, mas que está disposto a navegar como tempestades.",
    "Há sinais aqui de que você está destinado a viver amores que deixam marcas profundas, cicatrizes que, de alguma forma, tornam sua alma mais forte.",
    "Vejo um amor que transcende o tempo. Como se as mãos que você segura hoje, de alguma forma, já tenham tocado as suas em outras vidas.",
    "Suas mãos contam a história de um coração que não se cansa de amar, mesmo quando ferido. Há uma força em sua resiliência emocional.",
    "O amor não se mede apenas pelo tempo, mas pela profundidade da conexão. Suas mãos revelam que você está destinado a amar intensamente.",
    "Há uma dualidade em seu coração: o desejo por liberdade e o desejo por união. O amor verdadeiro para você será aquele que equilibra os dois.",
    "Uma reviravolta devastadora se aproxima, como uma tempestade que arrasará o que você construiu. Mas é nesse cenário de destruição que você descobrirá novas fundações, mais sólidas do que antes.",
    "Sua jornada está prestes a encontrar um ponto de ruptura, algo que parece impossível de suportar. Mas é nas ruínas desse momento que você encontra a chave para um renascimento grandioso.",
    "Há sinais de um colapso iminente, como se tudo o que você conhece fosse posto à prova. No entanto, as mesmas linhas que mostram esse desafio também revelam sua capacidade de transcender qualquer adversidade.",
    "O caminho que vejo aqui está marcado por uma perda significativa, um evento que mudará o curso de sua vida. Mas essa mudança será o acontecimento para sua maior evolução.",
    "Embora o destino traga uma prova severa à sua porta, o que vejo ao final dessa batalha é uma versão mais forte e imbatível de você mesmo.",
    "Uma tragédia acontecerá, como uma tragédia que varrerá tudo. Mas, após uma devastação, o que florescerá será algo que nem mesmo você sabia que poderia alcançar.",
    "As dificuldades que se aproximam parecem insuperáveis, como montanhas à frente. Mas suas mãos mostram que, ao escalar essas alturas, você verá o mundo de uma maneira que jamais imaginou.",
    "A vida vai desmoronar ao seu redor, como uma torre que desaba. Mas, das ruínas, você construirá algo ainda mais forte, algo que refletirá sua verdadeira essência.",
    "O destino reserva um teste amargo, um momento de dor profunda. Mas, ao atravessá-lo, você encontrará uma nova força que o conduzirá a um caminho de luz e triunfo.",
    "A vida te lançará em uma escuridão, como se você fosse mergulhar no abismo. Mas, ao emergir, você será transformado, com uma nova luz interior guiando seus passos.",
    "O que vejo é um colapso progressivo, algo que você não poderá evitar. No entanto, será a partir dessa destruição que você encontrará o caminho para sua verdadeira ascensão.",
    "As linhas da sua mão mostram uma tragédia iminente, uma fase de grande sofrimento. Mas é precisamente na profundidade dessa dor que sua alma se elevará, mais forte e mais luminosa do que nunca."
]





